# For more info on HTTP files go to https://aka.ms/vs/httpfile
@BASE_URL=http://localhost:5005/api
# @BASE_URL=https://localhost:7296/api


###
GET {{BASE_URL}}/user
content-type: application/json

###
POST {{BASE_URL}}/user/insert
content-type: application/json

{
    "FirstName": "F name",
    "LastName": "L name",
    "Phone": "2267915030",
    "Email": "mail@email.com",
    "Password": "1"
}

###
GET {{BASE_URL}}/user/e347f
content-type: application/json
